server:
  port: 8001

spring:
  application:
    name: runa

  profiles:
    active: dev

  main:
    allow-circular-references: true

  cloud:
    nacos:
      config:
        import-check:
          enabled: false
      discovery:
        enabled: false

  data:
    redis:
      host: 192.168.100.128
      port: 6379
      database: 1
      lettuce:
        pool:
          max-active: 300
          max-idle: 50
          min-idle: 10
          time-between-eviction-runs: 10s

qwen:
  api-key: sk-9542a01bce22464396b3c0d050afed68
  luna-id: ae8cc4b7551f4ddc8233e9666359a2ba
  summary-id: a427e617960545ab878de348075015f9

gemini:
  url: https://sunlea.de/v1/chat/completions
  api: sk-RmtnZlEJoyvcruF36uhXZfIQA0y1b2xtY8dFxY2yVcYeVcMl
  summary-model-name: gemini-3-flash-preview
  chat-model-name: gemini-2.5-pro

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs

knife4j:
  enable: true
  setting:
    language: zh_cn
