server:
  port: 8001

logging:
  level:
    dev.langchain4j: DEBUG
    org.yilena.luna: DEBUG

spring:
  application:
    name: runa

  profiles:
    active: dev

  main:
    allow-circular-references: true

  cloud:
    nacos:
      config:
        import-check:
          enabled: false
      discovery:
        enabled: false

  datasource:
    url: jdbc:postgresql://192.168.100.128:5432/luna
    username: yilena
    password: XUWENBO219382
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: 192.168.100.128
      port: 6379
      database: 1
      lettuce:
        pool:
          max-active: 300
          max-idle: 50
          min-idle: 10
          time-between-eviction-runs: 10s

qwen:
  api-key: sk-9542a01bce22464396b3c0d050afed68
  luna-id: ae8cc4b7551f4ddc8233e9666359a2ba
  summary-id: a427e617960545ab878de348075015f9

gemini:
  small:
    url: https://api.wataruu.me/v1/chat/completions
    api-key: sk-BOIfaNR9CVuERB57c
    model-name: gpt-5.2-codex
  mid:
    url: https://api.wataruu.me/v1/chat/completions
    api-key: sk-BOIfaNR9CVuERB57c
    model-name: gpt-5.2-codex
  big:
    url: https://catiecli.sukaka.top/v1/chat/completions
    api-key: sk-ant-bdd5aa945da3ceb5771d2300066a0390bb27b8abc02d725b
    model-name: gcli-gemini-3-pro-preview
  flash:
    url: https://api.wataruu.me/v1/chat/completions
    api-key: sk-BOIfaNR9CVuERB57c
    model-name: gpt-5.2-codex

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs

knife4j:
  enable: true
  setting:
    language: zh_cn

auth:
  username: Yilena
  password: XUWENBO219382

mybatis-plus:
  type-aliases-package: org.yilena.luna.*.entity
  type-handlers-package: com.baomidou.mybatisplus.extension.handlers
  mapper-locations: classpath:/mapper/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: deleted
    enable-sql-runner: true
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
    map-underscore-to-camel-case: true

embedding:
  python-path: D:/AI_Models/BGE-base-zh-v1.5/bge-env/Scripts/python.exe
  script-path: ./python/embedding.py
  model-path: D:/AI_Models/bge-base-zh-v1.5-model

serper:
  api-key: fe2bc5deb3372b8fc2823c2031e06a209e20bd75
