package org.yilena.luna.mq.consumer;

import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.apache.rocketmq.spring.annotation.RocketMQMessageListener;
import org.apache.rocketmq.spring.core.RocketMQListener;
import org.springframework.stereotype.Component;
import org.yilena.luna.constants.RocketMqConstant;
import org.yilena.luna.mq.dto.SummaryMessage;
import org.yilena.luna.service.TaskOrchestratorService;
import org.yilena.luna.service.model.SummaryOrchestrationResult;

@Slf4j
@Component
@RequiredArgsConstructor
@RocketMQMessageListener(topic = RocketMqConstant.TOPIC_SUMMARY, consumerGroup = RocketMqConstant.GROUP_SUMMARY)
public class ContextSummaryConsumer implements RocketMQListener<SummaryMessage> {

    private final TaskOrchestratorService taskOrchestratorService;

    @Override
    public void onMessage(SummaryMessage msg) {
        if (msg == null || msg.getSessionKey() == null || msg.getSessionKey().isBlank()) {
            return;
        }
        String sessionKey = msg.getSessionKey();
        try {
            SummaryOrchestrationResult summaryOrchestrationResult = taskOrchestratorService.orchestrateSummary(
                    sessionKey,
                    msg.getUserInput(),
                    msg.getAssistantReply(),
                    null,
                    java.util.List.of(),
                    java.util.List.of(),
                    null,
                    true,
                    firstNonBlank(msg.getTriggerSource(), "MQ_SUMMARY")
            );
            String narrative = summaryOrchestrationResult == null || summaryOrchestrationResult.getSummaryResult() == null
                    ? ""
                    : summaryOrchestrationResult.getSummaryResult().getNarrativeSummary();
            int snapshotSize = summaryOrchestrationResult == null
                    || summaryOrchestrationResult.getSummaryResult() == null
                    || summaryOrchestrationResult.getSummaryResult().getStateSnapshot() == null
                    ? 0
                    : summaryOrchestrationResult.getSummaryResult().getStateSnapshot().size();
            log.info("context summary generated by TaskOrchestrator, sessionKey={}, narrativePresent={}, snapshotSize={}",
                    sessionKey, narrative != null && !narrative.isBlank(), snapshotSize);
        } catch (Exception ex) {
            log.error("context summary failed, sessionKey={}, error={}", sessionKey, ex.getMessage(), ex);
        }
    }

    private String firstNonBlank(String first, String second) {
        if (first != null && !first.isBlank()) {
            return first;
        }
        if (second != null && !second.isBlank()) {
            return second;
        }
        return "";
    }
}
