package org.yilena.luna.mq.consumer;

import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.apache.rocketmq.spring.annotation.RocketMQMessageListener;
import org.apache.rocketmq.spring.core.RocketMQListener;
import org.springframework.stereotype.Component;
import org.yilena.luna.constants.RocketMqConstant;
import org.yilena.luna.context.SummaryAgent;
import org.yilena.luna.context.model.SummaryResult;
import org.yilena.luna.memory.ContextCompilerService;
import org.yilena.luna.memory.model.StructuredContextPackage;
import org.yilena.luna.mq.dto.SummaryMessage;
import org.yilena.luna.service.SessionService;

@Slf4j
@Component
@RequiredArgsConstructor
@RocketMQMessageListener(topic = RocketMqConstant.TOPIC_SUMMARY, consumerGroup = RocketMqConstant.GROUP_SUMMARY)
public class ContextSummaryConsumer implements RocketMQListener<SummaryMessage> {

    private final SummaryAgent summaryAgent;
    private final ContextCompilerService contextCompilerService;
    private final SessionService sessionService;

    @Override
    public void onMessage(SummaryMessage msg) {
        if (msg == null || msg.getSessionKey() == null || msg.getSessionKey().isBlank()) {
            return;
        }
        String sessionKey = msg.getSessionKey();
        try {
            StructuredContextPackage contextPackage = contextCompilerService.compile(sessionKey, "MQ_SUMMARY", null, null);
            SummaryResult summaryResult = summaryAgent.summarize("", "", contextPackage);
            String narrative = summaryResult == null ? "" : summaryResult.getNarrativeSummary();
            if (narrative != null && !narrative.isBlank()) {
                sessionService.replaceHistoryWithSummary(sessionKey, narrative);
                log.info("context summary generated by SummaryAgent, sessionKey={}", sessionKey);
            }
        } catch (Exception ex) {
            log.error("context summary failed, sessionKey={}, error={}", sessionKey, ex.getMessage(), ex);
        }
    }
}
