package org.yilena.luna.mq.consumer;

import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.apache.rocketmq.spring.annotation.RocketMQMessageListener;
import org.apache.rocketmq.spring.core.RocketMQListener;
import org.springframework.stereotype.Component;
import org.yilena.luna.constants.RocketMqConstant;
import org.yilena.luna.context.SummaryAgent;
import org.yilena.luna.context.SummaryTraceLogger;
import org.yilena.luna.context.model.SummaryResult;
import org.yilena.luna.memory.ContextCompilerService;
import org.yilena.luna.memory.model.StructuredContextPackage;
import org.yilena.luna.mq.dto.SummaryMessage;
import org.yilena.luna.service.SessionService;
import org.yilena.luna.state.model.ContextState;
import org.yilena.luna.state.store.ContextStateStore;

import java.util.List;
import java.util.Map;

@Slf4j
@Component
@RequiredArgsConstructor
@RocketMQMessageListener(topic = RocketMqConstant.TOPIC_SUMMARY, consumerGroup = RocketMqConstant.GROUP_SUMMARY)
public class ContextSummaryConsumer implements RocketMQListener<SummaryMessage> {

    private final SummaryAgent summaryAgent;
    private final ContextCompilerService contextCompilerService;
    private final SessionService sessionService;
    private final ContextStateStore contextStateStore;
    private final SummaryTraceLogger summaryTraceLogger;

    @Override
    public void onMessage(SummaryMessage msg) {
        if (msg == null || msg.getSessionKey() == null || msg.getSessionKey().isBlank()) {
            return;
        }
        String sessionKey = msg.getSessionKey();
        try {
            StructuredContextPackage contextPackage = contextCompilerService.compile(sessionKey, "MQ_SUMMARY", null, null);
            String summaryUserInput = firstNonBlank(
                    msg.getUserInput(),
                    latestMessageByRole(contextPackage, "USER")
            );
            String summaryAssistantReply = firstNonBlank(
                    msg.getAssistantReply(),
                    latestAssistantReply(contextPackage)
            );
            SummaryResult summaryResult = summaryAgent.summarize(
                    summaryUserInput,
                    summaryAssistantReply,
                    contextPackage,
                    List.of(),
                    List.of(),
                    null
            );
            String narrative = summaryResult == null ? "" : summaryResult.getNarrativeSummary();
            Map<String, Object> snapshot = summaryResult == null || summaryResult.getStateSnapshot() == null
                    ? Map.of()
                    : summaryResult.getStateSnapshot();

            if (narrative != null && !narrative.isBlank()) {
                sessionService.replaceHistoryWithSummary(sessionKey, narrative, snapshot.isEmpty() ? "" : snapshot.toString());
            }
            saveContextStateSummary(sessionKey, narrative, snapshot);
            summaryTraceLogger.log(
                    sessionKey,
                    contextPlanId(contextPackage),
                    contextNodeId(contextPackage),
                    summaryUserInput,
                    summaryAssistantReply,
                    contextPackage,
                    summaryResult,
                    firstNonBlank(msg.getTriggerSource(), "MQ_SUMMARY")
            );
            log.info("context summary generated by SummaryAgent, sessionKey={}, narrativePresent={}, snapshotSize={}",
                    sessionKey, narrative != null && !narrative.isBlank(), snapshot.size());
        } catch (Exception ex) {
            log.error("context summary failed, sessionKey={}, error={}", sessionKey, ex.getMessage(), ex);
        }
    }

    private void saveContextStateSummary(String sessionKey,
                                         String narrative,
                                         Map<String, Object> snapshot) {
        ContextState previous = contextStateStore.load(sessionKey);
        ContextState next = ContextState.builder()
                .latestNarrativeSummary(narrative == null ? "" : narrative)
                .latestStateSnapshot(snapshot == null ? Map.of() : snapshot)
                .activeKnowledgeRefs(previous == null ? List.of() : safeList(previous.getActiveKnowledgeRefs()))
                .activeMemoryRefs(previous == null ? List.of() : safeList(previous.getActiveMemoryRefs()))
                .activeToolEvidenceRefs(previous == null ? List.of() : safeList(previous.getActiveToolEvidenceRefs()))
                .activeMcpPromptRefs(previous == null ? List.of() : safeList(previous.getActiveMcpPromptRefs()))
                .activeMcpResourceRefs(previous == null ? List.of() : safeList(previous.getActiveMcpResourceRefs()))
                .latestContextSnapshotId(previous == null
                        ? ""
                        : previous.getLatestContextSnapshotId())
                .build();
        contextStateStore.save(sessionKey, next);
    }

    private List<String> safeList(List<String> value) {
        return value == null ? List.of() : List.copyOf(value);
    }

    private String latestMessageByRole(StructuredContextPackage contextPackage, String targetRole) {
        if (contextPackage == null || contextPackage.getRecentMessages() == null || targetRole == null) {
            return "";
        }
        for (int i = contextPackage.getRecentMessages().size() - 1; i >= 0; i--) {
            Map<String, Object> row = contextPackage.getRecentMessages().get(i);
            String role = stringValue(row.get("role"));
            if (targetRole.equalsIgnoreCase(role)) {
                return stringValue(row.get("content_text"));
            }
        }
        return "";
    }

    private String latestAssistantReply(StructuredContextPackage contextPackage) {
        String luna = latestMessageByRole(contextPackage, "LUNA");
        if (!luna.isBlank()) {
            return luna;
        }
        return latestMessageByRole(contextPackage, "ASSISTANT");
    }

    private Long contextPlanId(StructuredContextPackage contextPackage) {
        if (contextPackage == null || contextPackage.getRuntime() == null) {
            return null;
        }
        Object session = contextPackage.getRuntime().get("session");
        if (session instanceof Map<?, ?> row) {
            return parseLongValue(row.get("current_plan_id"));
        }
        return null;
    }

    private Long contextNodeId(StructuredContextPackage contextPackage) {
        if (contextPackage == null || contextPackage.getTaskContext() == null) {
            return null;
        }
        Object working = contextPackage.getTaskContext().get("working_memory");
        if (working instanceof Map<?, ?> row) {
            return parseLongValue(row.get("active_node_id"));
        }
        return null;
    }

    private Long parseLongValue(Object value) {
        if (value instanceof Number number) {
            return number.longValue();
        }
        if (value == null) {
            return null;
        }
        try {
            return Long.parseLong(String.valueOf(value));
        } catch (Exception ignore) {
            return null;
        }
    }

    private String stringValue(Object value) {
        return value == null ? "" : String.valueOf(value);
    }

    private String firstNonBlank(String first, String second) {
        if (first != null && !first.isBlank()) {
            return first;
        }
        if (second != null && !second.isBlank()) {
            return second;
        }
        return "";
    }
}
