#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Migrate MCP data via HTTP APIs using the SQL dump as source.

- Catalog upsert: POST /mcp/migrate/*

This script parses ._mcp_migration.sql and calls the APIs so IDs/embeddings
are generated by the service instead of direct SQL inserts.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
import time
from typing import Any, Dict, List, Optional, Set, Tuple

try:
    from urllib.request import Request, urlopen
    from urllib.error import HTTPError, URLError
except Exception as e:  # pragma: no cover
    print(f"Failed to import urllib: {e}", file=sys.stderr)
    sys.exit(1)

LOCAL_SERVER_CODE = "local-agent-server"


def read_text(path: str) -> str:
    with open(path, "r", encoding="utf-8", errors="replace") as f:
        return f.read()


def extract_values_block(sql: str, table: str) -> Optional[str]:
    # Capture between VALUES and ON CONFLICT (or terminating semicolon)
    pattern = re.compile(
        rf"INSERT\s+INTO\s+{re.escape(table)}\s*\([^;]*?\)\s*VALUES\s*(.*?)(?:\s*ON\s+CONFLICT|\s*;)",
        re.IGNORECASE | re.DOTALL,
    )
    m = pattern.search(sql)
    return m.group(1) if m else None


def extract_columns(sql: str, table: str) -> Optional[List[str]]:
    pattern = re.compile(
        rf"INSERT\s+INTO\s+{re.escape(table)}\s*\((.*?)\)\s*VALUES",
        re.IGNORECASE | re.DOTALL,
    )
    m = pattern.search(sql)
    if not m:
        return None
    cols_raw = m.group(1)
    cols = []
    for c in cols_raw.split(","):
        name = c.strip().strip('"')
        if name:
            cols.append(name)
    return cols


def parse_rows(values_text: str) -> List[List[Dict[str, Any]]]:
    rows: List[List[Dict[str, Any]]] = []
    i = 0
    n = len(values_text)
    while i < n:
        ch = values_text[i]
        if ch != "(":
            i += 1
            continue
        i += 1  # skip '('
        row: List[Dict[str, Any]] = []
        while i < n:
            # skip whitespace
            while i < n and values_text[i].isspace():
                i += 1
            if i >= n:
                break
            if values_text[i] == ")":
                i += 1
                break
            val, i = parse_value(values_text, i)
            row.append(val)
            # skip whitespace
            while i < n and values_text[i].isspace():
                i += 1
            if i < n and values_text[i] == ",":
                i += 1
                continue
            if i < n and values_text[i] == ")":
                i += 1
                break
        if row:
            rows.append(row)
    return rows


def parse_value(text: str, i: int) -> Tuple[Dict[str, Any], int]:
    if text.startswith("$json$", i):
        i += 6
        j = text.find("$json$", i)
        if j == -1:
            raise ValueError("Unclosed $json$ block")
        content = text[i:j]
        i = j + 6
        if text.startswith("::jsonb", i):
            i += 7
        return {"type": "json", "value": content}, i
    if text[i] == "'":
        i += 1
        out = []
        while i < len(text):
            if text[i] == "'":
                if i + 1 < len(text) and text[i + 1] == "'":
                    out.append("'")
                    i += 2
                    continue
                i += 1
                break
            out.append(text[i])
            i += 1
        if text.startswith("::jsonb", i):
            i += 7
        return {"type": "string", "value": "".join(out)}, i
    # raw value
    start = i
    while i < len(text) and text[i] not in [",", ")"]:
        i += 1
    raw = text[start:i].strip()
    if raw.endswith("::jsonb"):
        raw = raw[:-7].strip()
    return {"type": "raw", "value": raw}, i


def parse_insert(sql: str, table: str) -> Tuple[List[str], List[Dict[str, Any]]]:
    cols = extract_columns(sql, table) or []
    block = extract_values_block(sql, table)
    if not block or not cols:
        return [], []
    rows = parse_rows(block)
    out = []
    for r in rows:
        vals = [convert_token(t) for t in r]
        row_map: Dict[str, Any] = {}
        for idx, col in enumerate(cols):
            row_map[col] = vals[idx] if idx < len(vals) else None
        out.append(row_map)
    return cols, out


def snake_to_camel(s: str) -> str:
    # normalize legacy/alt column names
    if s in ("route_url", "route_uri"):
        return "routeUri"
    if s in ("route_policy", "retry_policy"):
        return "retryPolicy"
    parts = s.split("_")
    return parts[0] + "".join(p[:1].upper() + p[1:] for p in parts[1:] if p)


def keys_to_camel(d: Dict[str, Any]) -> Dict[str, Any]:
    out: Dict[str, Any] = {}
    for k, v in d.items():
        ck = snake_to_camel(k)
        if ck == "embedding" and v is not None and not isinstance(v, str):
            out[ck] = json.dumps(v, ensure_ascii=False)
        else:
            out[ck] = v
    return out


def parse_json_file(path: str) -> Dict[str, Any]:
    try:
        with open(path, "r", encoding="utf-8", errors="replace") as f:
            return json.load(f)
    except Exception:
        return {}


def parse_json_files_in_dir(path: str) -> List[Dict[str, Any]]:
    out: List[Dict[str, Any]] = []
    if not path or not os.path.isdir(path):
        return out
    for name in os.listdir(path):
        if not name.lower().endswith(".json"):
            continue
        p = os.path.join(path, name)
        item = parse_json_file(p)
        if item:
            out.append(item)
    return out


def parse_json_array_file(path: str) -> List[Dict[str, Any]]:
    if not path or not os.path.isfile(path):
        return []
    try:
        with open(path, "r", encoding="utf-8", errors="replace") as f:
            data = json.load(f)
        if isinstance(data, list):
            return [it for it in data if isinstance(it, dict)]
    except Exception:
        pass
    return []


def write_json_file(path: str, data: Any) -> None:
    parent = os.path.dirname(path)
    if parent:
        os.makedirs(parent, exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)


def is_workflow_skill_item(item: Dict[str, Any]) -> bool:
    run_mode = str(item.get("run_mode") or item.get("runMode") or "").upper()
    req_caps = item.get("required_capabilities") or item.get("requiredCapabilities")
    tool_slots = item.get("tool_slots") or item.get("toolSlots")
    thought_chain = item.get("thought_chain") or item.get("thoughtChain")
    return (
        run_mode == "ASYNC"
        or (isinstance(req_caps, list) and len(req_caps) > 0)
        or (isinstance(tool_slots, list) and len(tool_slots) > 0)
        or (isinstance(thought_chain, list) and len(thought_chain) > 0)
    )


def split_skill_items(skill_items: List[Dict[str, Any]]) -> Tuple[List[Dict[str, Any]], List[Dict[str, Any]]]:
    workflow: List[Dict[str, Any]] = []
    non_workflow: List[Dict[str, Any]] = []
    seen: Set[str] = set()
    for item in skill_items:
        name = item.get("name") or item.get("skill_name") or item.get("workflow_name")
        if not name:
            continue
        key = str(name).strip()
        if not key or key in seen:
            continue
        seen.add(key)
        normalized = dict(item)
        normalized["name"] = key
        if is_workflow_skill_item(item):
            workflow.append(normalized)
        else:
            non_workflow.append(normalized)
    return non_workflow, workflow


def synthesize_prompt_rows(
    prompt_rows: List[Dict[str, Any]],
    legacy_skill_rows: List[Dict[str, Any]],
    skill_json_rows: List[Dict[str, Any]],
    include_workflow: bool,
) -> List[Dict[str, Any]]:
    if prompt_rows:
        return prompt_rows
    out: List[Dict[str, Any]] = []
    seen: Set[str] = set()
    for item in legacy_skill_rows + skill_json_rows:
        if (not include_workflow) and is_workflow_skill_item(item):
            continue
        name = item.get("name") or item.get("prompt_name")
        if not name:
            continue
        key = str(name).strip()
        if not key or key in seen:
            continue
        seen.add(key)
        out.append(
            {
                "server_code": item.get("server_code") or LOCAL_SERVER_CODE,
                "prompt_name": key,
                "title": key,
                "description": item.get("description"),
                "arguments_schema": item.get("input_schema") or item.get("inputSchema") or {},
                "raw_payload": {
                    "skillName": key,
                    "legacyBeanName": item.get("bean_name") or item.get("beanName") or "",
                    "legacyMethodName": item.get("method_name") or item.get("methodName") or "",
                    "runMode": str(item.get("run_mode") or item.get("runMode") or "SYNC").upper(),
                },
                "enabled": bool(item.get("enabled", True)),
                "version": item.get("version") or "1.0.0",
                "embedding": item.get("embedding"),
            }
        )
    return out


def synthesize_resource_rows(
    resource_rows: List[Dict[str, Any]],
    resource_json_rows: List[Dict[str, Any]],
) -> List[Dict[str, Any]]:
    if resource_rows:
        return resource_rows
    out: List[Dict[str, Any]] = []
    seen: Set[str] = set()
    for item in resource_json_rows:
        uri = item.get("resourceUri") or item.get("resource_uri") or item.get("uri")
        if not uri:
            continue
        key = str(uri).strip()
        if not key or key in seen:
            continue
        seen.add(key)
        out.append(
            {
                "server_code": item.get("serverCode") or item.get("server_code") or LOCAL_SERVER_CODE,
                "resource_uri": key,
                "name": item.get("name"),
                "description": item.get("description"),
                "mime_type": item.get("mimeType") or item.get("mime_type"),
                "annotations": item.get("annotations") or {},
                "raw_payload": item.get("rawPayload") or item.get("raw_payload") or item,
                "tags": item.get("tags") or [],
                "enabled": bool(item.get("enabled", True)),
                "embedding": item.get("embedding"),
            }
        )
    return out


def build_tool_payload_from_row(row: Dict[str, Any]) -> Optional[Dict[str, Any]]:
    # Prefer raw_payload when present (contains beanName/methodName)
    raw = row.get("raw_payload") if isinstance(row, dict) else None
    if isinstance(raw, str):
        try:
            raw = json.loads(raw)
        except Exception:
            raw = None
    payload = {
        "name": row.get("tool_name") or row.get("name") or (raw.get("name") if isinstance(raw, dict) else None),
        "description": row.get("description") or (raw.get("description") if isinstance(raw, dict) else None),
        "version": row.get("version") or (raw.get("version") if isinstance(raw, dict) else None),
        "owner": row.get("owner") or (raw.get("owner") if isinstance(raw, dict) else None),
        "beanName": row.get("bean_name") or (raw.get("beanName") if isinstance(raw, dict) else None),
        "methodName": row.get("method_name") or (raw.get("methodName") if isinstance(raw, dict) else None),
        "inputSchema": row.get("input_schema") or (raw.get("inputSchema") if isinstance(raw, dict) else None),
        "outputSchema": row.get("output_schema") or (raw.get("outputSchema") if isinstance(raw, dict) else None),
        "requiresApproval": row.get("requires_approval") or (raw.get("requiresApproval") if isinstance(raw, dict) else None),
        "sensitivity": row.get("sensitivity") or (raw.get("sensitivity") if isinstance(raw, dict) else None),
    }
    for key in ("inputSchema", "outputSchema"):
        v = payload.get(key)
        if v is not None and not isinstance(v, str):
            payload[key] = json.dumps(v, ensure_ascii=False)
    if not payload.get("name") or not payload.get("beanName") or not payload.get("methodName"):
        return None
    return payload


def build_skill_payload_from_row(row: Dict[str, Any]) -> Optional[Dict[str, Any]]:
    payload = {
        "name": row.get("name") or row.get("skill_name") or row.get("workflow_name"),
        "description": row.get("description"),
        "version": row.get("version"),
        "owner": row.get("owner"),
        "beanName": row.get("bean_name"),
        "methodName": row.get("method_name"),
        "inputSchema": row.get("input_schema"),
        "outputSchema": row.get("output_schema"),
        "runMode": row.get("run_mode"),
        "requiredCapabilities": row.get("required_capabilities"),
        "toolSlots": row.get("tool_slots"),
        "thoughtChain": row.get("thought_chain"),
    }
    for key in ("inputSchema", "outputSchema"):
        v = payload.get(key)
        if v is not None and not isinstance(v, str):
            payload[key] = json.dumps(v, ensure_ascii=False)
    if not payload.get("name"):
        return None
    return payload


def parse_json_content(content: str) -> Any:
    try:
        obj = json.loads(content)
        if isinstance(obj, str):
            try:
                obj2 = json.loads(obj)
                return obj2
            except Exception:
                return obj
        return obj
    except Exception:
        # Treat as plain string when not valid JSON
        return content


def convert_token(tok: Dict[str, Any]) -> Any:
    t = tok["type"]
    v = tok["value"]
    if t == "json":
        return parse_json_content(v)
    if t == "string":
        s = v
        if isinstance(s, str):
            st = s.strip()
            if (st.startswith("{") and st.endswith("}")) or (st.startswith("[") and st.endswith("]")):
                try:
                    return json.loads(st)
                except Exception:
                    return s
        return s
    raw = v
    if raw == "" or raw.upper() == "NULL":
        return None
    low = raw.lower()
    if low == "true":
        return True
    if low == "false":
        return False
    # Try JSON for raw-looking arrays/objects
    if raw.startswith("[") or raw.startswith("{") or raw.startswith("\""):
        try:
            return json.loads(raw)
        except Exception:
            return raw
    # Try number
    try:
        if "." in raw:
            return float(raw)
        return int(raw)
    except Exception:
        return raw


def http_post_json(url: str, payload: Dict[str, Any], headers: Dict[str, str], timeout: int) -> Tuple[int, str]:
    data = json.dumps(payload, ensure_ascii=False).encode("utf-8")
    req = Request(url, data=data, method="POST")
    req.add_header("Content-Type", "application/json")
    for k, v in headers.items():
        req.add_header(k, v)
    try:
        with urlopen(req, timeout=timeout) as resp:
            body = resp.read().decode("utf-8", errors="replace")
            return resp.status, body
    except HTTPError as e:
        body = e.read().decode("utf-8", errors="replace")
        return e.code, body
    except URLError as e:
        return 0, str(e)


def main() -> int:
    parser = argparse.ArgumentParser(description="Migrate MCP data via API from SQL dump.")
    parser.add_argument("--sql-file", default="._mcp_migration.sql", help="Path to SQL file")
    parser.add_argument("--base-url", default="http://localhost:8080", help="Base URL, e.g. http://localhost:8080")
    parser.add_argument("--token", default="", help="Bearer token (optional)")
    parser.add_argument("--timeout", type=int, default=20, help="HTTP timeout seconds")
    parser.add_argument("--dry-run", action="store_true", help="Parse only, do not call APIs")
    parser.add_argument("--skip-server", action="store_true", help="Skip mcp_server_registry migration")
    parser.add_argument("--skip-tool-catalog", action="store_true", help="Skip mcp_tool_catalog migration")
    parser.add_argument("--skip-tool-impl", action="store_true", help="Skip mcp_tool_impl_mapping migration")
    parser.add_argument("--skip-prompt-catalog", action="store_true", help="Skip mcp_prompt_catalog migration")
    parser.add_argument("--skip-resource-catalog", action="store_true", help="Skip mcp_resource_catalog migration")
    parser.add_argument("--skip-workflow", action="store_true", help="Skip workflow_template migration")
    parser.add_argument("--backfill-tools", action="store_true", help="Backfill tool catalog/impl mapping via /mcp/migrate/* (no legacy endpoints)")
    parser.add_argument("--backfill-skills", action="store_true", help="Backfill prompt/workflow catalogs via /mcp/migrate/* (no legacy endpoints)")
    parser.add_argument("--sync-json", action="store_true", help="Call /mcp/catalog/sync to load json/tool and json/skill")
    parser.add_argument("--skill-json-dir", default="json/skill", help="Skill json directory for prompt source synthesis")
    parser.add_argument("--resource-json-dir", default="json/resource", help="Resource json directory for resource source synthesis")
    parser.add_argument("--non-workflow-skill-source", default="scripts/migration_sources/skills_non_workflow.json", help="Non-workflow skill source file")
    parser.add_argument("--workflow-skill-source", default="scripts/migration_sources/skills_workflow.json", help="Workflow skill source file")
    parser.add_argument("--export-skill-sources", action="store_true", help="Export classified skill source files and continue")
    parser.add_argument("--prompt-from-all-skills", action="store_true", help="Generate prompt source from all skills (including workflow-like skills)")
    parser.add_argument("--sleep-ms", type=int, default=0, help="Sleep between requests (ms)")
    args = parser.parse_args()

    sql_path = args.sql_file
    if not os.path.isfile(sql_path):
        print(f"SQL file not found: {sql_path}", file=sys.stderr)
        return 2

    sql = read_text(sql_path)
    _, server_rows = parse_insert(sql, "mcp_server_registry")
    _, tool_rows = parse_insert(sql, "mcp_tool_catalog")
    _, impl_rows = parse_insert(sql, "mcp_tool_impl_mapping")
    _, prompt_rows = parse_insert(sql, "mcp_prompt_catalog")
    _, resource_rows = parse_insert(sql, "mcp_resource_catalog")
    _, workflow_rows = parse_insert(sql, "workflow_template")
    _, legacy_tool_rows = parse_insert(sql, "mcp_tools")
    _, legacy_skill_rows = parse_insert(sql, "mcp_skills")
    skill_json_rows = parse_json_files_in_dir(args.skill_json_dir)
    resource_json_rows = parse_json_files_in_dir(args.resource_json_dir)
    non_workflow_source_rows = parse_json_array_file(args.non_workflow_skill_source)
    workflow_source_rows = parse_json_array_file(args.workflow_skill_source)

    if args.export_skill_sources:
        base_skill_items: List[Dict[str, Any]] = []
        base_skill_items.extend(legacy_skill_rows)
        base_skill_items.extend(skill_json_rows)
        # workflow_template rows are also workflow skill sources
        for w in workflow_rows:
            mapped = {
                "name": w.get("workflow_name"),
                "description": w.get("description"),
                "version": w.get("version"),
                "input_schema": w.get("input_schema"),
                "output_schema": w.get("output_schema"),
                "required_capabilities": w.get("required_capabilities"),
                "tool_slots": w.get("tool_slots"),
                "thought_chain": w.get("thought_chain"),
                "run_mode": "ASYNC",
            }
            base_skill_items.append(mapped)
        non_workflow_export, workflow_export = split_skill_items(base_skill_items)
        write_json_file(args.non_workflow_skill_source, non_workflow_export)
        write_json_file(args.workflow_skill_source, workflow_export)
        print(
            f"[export_skill_sources] non_workflow={len(non_workflow_export)} -> {args.non_workflow_skill_source}; "
            f"workflow={len(workflow_export)} -> {args.workflow_skill_source}"
        )
        non_workflow_source_rows = non_workflow_export
        workflow_source_rows = workflow_export

    # Prefer explicit source files when provided
    if non_workflow_source_rows:
        if args.prompt_from_all_skills:
            prompt_rows = synthesize_prompt_rows(prompt_rows, non_workflow_source_rows + workflow_source_rows, [], True)
        else:
            prompt_rows = synthesize_prompt_rows(prompt_rows, non_workflow_source_rows, [], False)
    else:
        prompt_rows = synthesize_prompt_rows(prompt_rows, legacy_skill_rows, skill_json_rows, args.prompt_from_all_skills)

    # Fill workflow rows from explicit workflow source if SQL lacks workflow_template
    if not workflow_rows and workflow_source_rows:
        for item in workflow_source_rows:
            workflow_rows.append(
                {
                    "workflow_name": item.get("name") or item.get("workflow_name"),
                    "description": item.get("description"),
                    "input_schema": item.get("input_schema") or item.get("inputSchema"),
                    "output_schema": item.get("output_schema") or item.get("outputSchema"),
                    "required_capabilities": item.get("required_capabilities") or item.get("requiredCapabilities") or [],
                    "tool_slots": item.get("tool_slots") or item.get("toolSlots") or [],
                    "thought_chain": item.get("thought_chain") or item.get("thoughtChain") or [],
                    "blueprint_json": item.get("blueprint_json") or item.get("blueprintJson"),
                    "enabled": item.get("enabled", True),
                    "version": item.get("version") or "1.0.0",
                    "embedding": item.get("embedding"),
                }
            )

    resource_rows = synthesize_resource_rows(resource_rows, resource_json_rows)

    print(
        "Parsed: "
        f"server={len(server_rows)}, "
        f"tools={len(tool_rows)}, "
        f"impl={len(impl_rows)}, "
        f"prompts={len(prompt_rows)}, "
        f"resources={len(resource_rows)}, "
        f"workflows={len(workflow_rows)}, "
        f"legacy_tools={len(legacy_tool_rows)}, "
        f"legacy_skills={len(legacy_skill_rows)}, "
        f"skill_json={len(skill_json_rows)}, "
        f"resource_json={len(resource_json_rows)}, "
        f"non_workflow_source={len(non_workflow_source_rows)}, "
        f"workflow_source={len(workflow_source_rows)}"
    )
    if not prompt_rows:
        print("[prompt_catalog] no source found in SQL(mcp_prompt_catalog), SQL(mcp_skills), or json/skill")
    if not resource_rows:
        print("[resource_catalog] no source found in SQL(mcp_resource_catalog) or json/resource")
    if args.dry_run:
        return 0

    headers = {}
    if args.token:
        headers["Authorization"] = f"Bearer {args.token}"

    base = args.base_url.rstrip("/")
    ok_server = 0
    ok_tools = 0
    ok_impl = 0
    ok_prompts = 0
    ok_resources = 0
    ok_workflows = 0
    failed = 0

    if not args.skip_server:
        for r in server_rows:
            payload = keys_to_camel(r)
            if not payload.get("serverCode"):
                print("[server] skip missing serverCode")
                failed += 1
                continue
            url = f"{base}/mcp/migrate/server-registry"
            status, body = http_post_json(url, payload, headers, args.timeout)
            if status and 200 <= status < 300:
                ok_server += 1
            else:
                failed += 1
                print(f"[server] failed {payload.get('serverCode')} status={status} body={body[:300]}")
            if args.sleep_ms > 0:
                time.sleep(args.sleep_ms / 1000.0)

    if not args.skip_tool_catalog:
        for r in tool_rows:
            payload = keys_to_camel(r)
            if not payload.get("serverCode") or not payload.get("toolName"):
                print("[tool_catalog] skip missing serverCode/toolName")
                failed += 1
                continue
            url = f"{base}/mcp/migrate/tool-catalog"
            status, body = http_post_json(url, payload, headers, args.timeout)
            if status and 200 <= status < 300:
                ok_tools += 1
            else:
                failed += 1
                print(f"[tool_catalog] failed {payload.get('toolName')} status={status} body={body[:300]}")
            if args.sleep_ms > 0:
                time.sleep(args.sleep_ms / 1000.0)

    if not args.skip_tool_impl:
        for r in impl_rows:
            payload = keys_to_camel(r)
            if not payload.get("serverCode") or not payload.get("toolName"):
                print("[tool_impl] skip missing serverCode/toolName")
                failed += 1
                continue
            url = f"{base}/mcp/migrate/tool-impl-mapping"
            status, body = http_post_json(url, payload, headers, args.timeout)
            if status and 200 <= status < 300:
                ok_impl += 1
            else:
                failed += 1
                print(f"[tool_impl] failed {payload.get('toolName')} status={status} body={body[:300]}")
            if args.sleep_ms > 0:
                time.sleep(args.sleep_ms / 1000.0)

    if not args.skip_prompt_catalog:
        for r in prompt_rows:
            payload = keys_to_camel(r)
            if not payload.get("serverCode") or not payload.get("promptName"):
                print("[prompt_catalog] skip missing serverCode/promptName")
                failed += 1
                continue
            url = f"{base}/mcp/migrate/prompt-catalog"
            status, body = http_post_json(url, payload, headers, args.timeout)
            if status and 200 <= status < 300:
                ok_prompts += 1
            else:
                failed += 1
                print(f"[prompt_catalog] failed {payload.get('promptName')} status={status} body={body[:300]}")
            if args.sleep_ms > 0:
                time.sleep(args.sleep_ms / 1000.0)

    if not args.skip_resource_catalog:
        for r in resource_rows:
            payload = keys_to_camel(r)
            if not payload.get("serverCode") or not payload.get("resourceUri"):
                print("[resource_catalog] skip missing serverCode/resourceUri")
                failed += 1
                continue
            url = f"{base}/mcp/migrate/resource-catalog"
            status, body = http_post_json(url, payload, headers, args.timeout)
            if status and 200 <= status < 300:
                ok_resources += 1
            else:
                failed += 1
                print(f"[resource_catalog] failed {payload.get('resourceUri')} status={status} body={body[:300]}")
            if args.sleep_ms > 0:
                time.sleep(args.sleep_ms / 1000.0)

    if not args.skip_workflow:
        for r in workflow_rows:
            payload = keys_to_camel(r)
            if not payload.get("workflowName"):
                print("[workflow_template] skip missing workflowName")
                failed += 1
                continue
            url = f"{base}/mcp/migrate/workflow-template"
            status, body = http_post_json(url, payload, headers, args.timeout)
            if status and 200 <= status < 300:
                ok_workflows += 1
            else:
                failed += 1
                print(f"[workflow_template] failed {payload.get('workflowName')} status={status} body={body[:300]}")
            if args.sleep_ms > 0:
                time.sleep(args.sleep_ms / 1000.0)

    # Optional: sync json catalog (json/tool + json/skill) via server
    if args.sync_json:
        url = f"{base}/mcp/catalog/sync"
        status, body = http_post_json(url, {}, headers, args.timeout)
        if status and 200 <= status < 300:
            print(f"[sync_json] ok status={status}")
        else:
            failed += 1
            print(f"[sync_json] failed status={status} body={body[:300]}")

    # Optional: backfill tools via migrate endpoints
    if args.backfill_tools:
        source_rows = legacy_tool_rows if legacy_tool_rows else tool_rows
        for r in source_rows:
            raw = r.get("raw_payload")
            if isinstance(raw, str):
                try:
                    raw = json.loads(raw)
                except Exception:
                    raw = {}
            if not isinstance(raw, dict):
                raw = {}

            server_code = r.get("server_code") or raw.get("serverCode") or LOCAL_SERVER_CODE
            tool_name = r.get("tool_name") or r.get("name") or raw.get("name")
            if not tool_name:
                print("[backfill_tools] skip missing tool_name")
                failed += 1
                continue

            tool_payload = {
                "serverCode": server_code,
                "toolName": tool_name,
                "title": r.get("title") or tool_name,
                "description": r.get("description") or raw.get("description"),
                "inputSchema": r.get("input_schema") or raw.get("inputSchema") or {},
                "outputSchema": r.get("output_schema") or raw.get("outputSchema") or {},
                "enabled": r.get("enabled", True),
                "version": r.get("version") or raw.get("version") or "1.0.0",
                "requiresApproval": r.get("requires_approval") if "requires_approval" in r else raw.get("requiresApproval", False),
                "sensitivity": r.get("sensitivity") or raw.get("sensitivity") or "LOW",
                "rawPayload": raw if raw else None,
                "embedding": r.get("embedding"),
            }
            status, body = http_post_json(f"{base}/mcp/migrate/tool-catalog", tool_payload, headers, args.timeout)
            if status and 200 <= status < 300:
                ok_tools += 1
            else:
                failed += 1
                print(f"[backfill_tools] tool-catalog failed {tool_name} status={status} body={body[:300]}")

            impl_payload = {
                "serverCode": server_code,
                "toolName": tool_name,
                "implType": r.get("impl_type") or "SPRING_BEAN",
                "beanName": r.get("bean_name") or raw.get("beanName"),
                "methodName": r.get("method_name") or raw.get("methodName"),
                "routeUri": r.get("route_uri"),
                "timeoutMs": r.get("timeout_ms") or 10000,
                "retryPolicy": r.get("retry_policy"),
                "enabled": r.get("enabled", True),
            }
            if impl_payload.get("beanName") or impl_payload.get("routeUri"):
                status2, body2 = http_post_json(f"{base}/mcp/migrate/tool-impl-mapping", impl_payload, headers, args.timeout)
                if status2 and 200 <= status2 < 300:
                    ok_impl += 1
                else:
                    failed += 1
                    print(f"[backfill_tools] tool-impl failed {tool_name} status={status2} body={body2[:300]}")
            if args.sleep_ms > 0:
                time.sleep(args.sleep_ms / 1000.0)

    # Optional: backfill skills via migrate endpoints
    if args.backfill_skills:
        source_rows = legacy_skill_rows if legacy_skill_rows else workflow_rows
        for r in source_rows:
            name = r.get("name") or r.get("workflow_name") or r.get("prompt_name")
            if not name:
                print("[backfill_skills] skip missing name")
                failed += 1
                continue
            server_code = r.get("server_code") or LOCAL_SERVER_CODE
            if is_workflow_skill_item(r):
                workflow_payload = {
                    "workflowName": name,
                    "description": r.get("description"),
                    "inputSchema": r.get("input_schema") or r.get("inputSchema") or {},
                    "outputSchema": r.get("output_schema") or r.get("outputSchema") or {},
                    "requiredCapabilities": r.get("required_capabilities") or r.get("requiredCapabilities") or [],
                    "toolSlots": r.get("tool_slots") or r.get("toolSlots") or [],
                    "thoughtChain": r.get("thought_chain") or r.get("thoughtChain") or [],
                    "blueprintJson": r.get("blueprint_json") or r.get("blueprintJson"),
                    "enabled": r.get("enabled", True),
                    "version": r.get("version") or "1.0.0",
                    "embedding": r.get("embedding"),
                }
                status, body = http_post_json(f"{base}/mcp/migrate/workflow-template", workflow_payload, headers, args.timeout)
                if status and 200 <= status < 300:
                    ok_workflows += 1
                else:
                    failed += 1
                    print(f"[backfill_skills] workflow failed {name} status={status} body={body[:300]}")
            else:
                prompt_payload = {
                    "serverCode": server_code,
                    "promptName": name,
                    "title": name,
                    "description": r.get("description"),
                    "argumentsSchema": r.get("input_schema") or r.get("inputSchema") or {},
                    "rawPayload": {
                        "skillName": name,
                        "legacyBeanName": r.get("bean_name") or r.get("beanName") or "",
                        "legacyMethodName": r.get("method_name") or r.get("methodName") or "",
                        "runMode": str(r.get("run_mode") or r.get("runMode") or "SYNC").upper(),
                    },
                    "enabled": r.get("enabled", True),
                    "version": r.get("version") or "1.0.0",
                    "embedding": r.get("embedding"),
                }
                status, body = http_post_json(f"{base}/mcp/migrate/prompt-catalog", prompt_payload, headers, args.timeout)
                if status and 200 <= status < 300:
                    ok_prompts += 1
                else:
                    failed += 1
                    print(f"[backfill_skills] prompt failed {name} status={status} body={body[:300]}")
            if args.sleep_ms > 0:
                time.sleep(args.sleep_ms / 1000.0)

    print(
        "Done. "
        f"server_ok={ok_server}, "
        f"tool_catalog_ok={ok_tools}, "
        f"tool_impl_ok={ok_impl}, "
        f"prompt_ok={ok_prompts}, "
        f"resource_ok={ok_resources}, "
        f"workflow_ok={ok_workflows}, "
        f"failed={failed}"
    )
    if failed > 0:
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
