#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Reassign MCP tools to multiple servers via HTTP APIs (no direct SQL updates).

Why this script:
- IDs are generated by service insert logic.
- Embeddings are generated by `/mcp/tools` registration path.
"""

from __future__ import annotations

import argparse
import json
import os
import sys
import time
from typing import Any, Dict, List, Optional, Tuple

try:
    from urllib.request import Request, urlopen
    from urllib.error import HTTPError, URLError
except Exception as e:  # pragma: no cover
    print(f"Failed to import urllib: {e}", file=sys.stderr)
    sys.exit(1)


LOCAL_SERVER_CODE = "local-agent-server"


def read_json(path: str) -> Dict[str, Any]:
    with open(path, "r", encoding="utf-8", errors="replace") as f:
        data = json.load(f)
    if not isinstance(data, dict):
        raise ValueError(f"json root must be object: {path}")
    return data


def read_tool_json(tool_dir: str, tool_name: str) -> Dict[str, Any]:
    path = os.path.join(tool_dir, f"{tool_name}.json")
    if not os.path.isfile(path):
        raise FileNotFoundError(f"tool json not found: {path}")
    return read_json(path)


def http_post_json(url: str, payload: Dict[str, Any], headers: Dict[str, str], timeout: int) -> Tuple[int, str]:
    data = json.dumps(payload, ensure_ascii=False).encode("utf-8")
    req = Request(url, data=data, method="POST")
    req.add_header("Content-Type", "application/json")
    for k, v in headers.items():
        req.add_header(k, v)
    try:
        with urlopen(req, timeout=timeout) as resp:
            body = resp.read().decode("utf-8", errors="replace")
            return resp.status, body
    except HTTPError as e:
        body = e.read().decode("utf-8", errors="replace")
        return e.code, body
    except URLError as e:
        return 0, str(e)


def safe_json_loads(text: str) -> Dict[str, Any]:
    try:
        obj = json.loads(text)
        return obj if isinstance(obj, dict) else {}
    except Exception:
        return {}


def build_register_tool_payload(tool_json: Dict[str, Any]) -> Dict[str, Any]:
    return {
        "name": tool_json.get("name"),
        "description": tool_json.get("description"),
        "version": tool_json.get("version") or "1.0.0",
        "owner": tool_json.get("owner"),
        "beanName": tool_json.get("beanName"),
        "methodName": tool_json.get("methodName"),
        "inputSchema": json.dumps(tool_json.get("inputSchema") or {}, ensure_ascii=False),
        "outputSchema": json.dumps(tool_json.get("outputSchema") or {}, ensure_ascii=False),
        "requiresApproval": bool(tool_json.get("requiresApproval", False)),
        "sensitivity": tool_json.get("sensitivity") or "LOW",
    }


def build_tool_catalog_payload(
    server_code: str,
    tool_name: str,
    tool_json: Dict[str, Any],
    embedding: Optional[str],
    enabled: bool,
) -> Dict[str, Any]:
    return {
        "serverCode": server_code,
        "toolName": tool_name,
        "title": tool_json.get("name") or tool_name,
        "description": tool_json.get("description"),
        "inputSchema": tool_json.get("inputSchema") or {},
        "outputSchema": tool_json.get("outputSchema") or {},
        "annotations": tool_json.get("annotations"),
        "tags": tool_json.get("tags") or [],
        "enabled": enabled,
        "version": tool_json.get("version") or "1.0.0",
        "requiresApproval": bool(tool_json.get("requiresApproval", False)),
        "sensitivity": tool_json.get("sensitivity") or "LOW",
        "rawPayload": tool_json,
        "embedding": embedding,
    }


def build_impl_mapping_payload(server_code: str, tool_name: str, tool_json: Dict[str, Any], enabled: bool) -> Dict[str, Any]:
    route_uri = tool_json.get("routeUri")
    if route_uri is None:
        route_uri = tool_json.get("route_url")
    retry_policy = tool_json.get("retryPolicy")
    if retry_policy is None:
        retry_policy = tool_json.get("route_policy")
    if retry_policy is None:
        retry_policy = tool_json.get("retry_policy")
    return {
        "serverCode": server_code,
        "toolName": tool_name,
        "implType": tool_json.get("implType") or "SPRING_BEAN",
        "beanName": tool_json.get("beanName"),
        "methodName": tool_json.get("methodName"),
        "routeUri": route_uri,
        "retryPolicy": retry_policy,
        "timeoutMs": int(tool_json.get("timeoutMs") or 10000),
        "enabled": enabled,
    }


def main() -> int:
    parser = argparse.ArgumentParser(description="Reassign MCP tools to target servers via API.")
    parser.add_argument(
        "--source",
        default="scripts/migration_sources/tool_server_assignment.json",
        help="Assignment source json file",
    )
    parser.add_argument(
        "--tool-json-dir",
        default="json/tool",
        help="Tool json directory",
    )
    parser.add_argument("--base-url", default="http://localhost:8080", help="Base URL of service")
    parser.add_argument("--token", default="", help="Bearer token")
    parser.add_argument("--timeout", type=int, default=20, help="HTTP timeout seconds")
    parser.add_argument("--sleep-ms", type=int, default=0, help="Sleep between requests (ms)")
    parser.add_argument("--disable-local", action="store_true", help="Disable local-agent-server tool rows after copy")
    parser.add_argument("--dry-run", action="store_true", help="Validate and print plan only")
    args = parser.parse_args()

    if not os.path.isfile(args.source):
        print(f"source file not found: {args.source}", file=sys.stderr)
        return 2
    if not os.path.isdir(args.tool_json_dir):
        print(f"tool json dir not found: {args.tool_json_dir}", file=sys.stderr)
        return 2

    source = read_json(args.source)
    servers = source.get("servers") or []
    assignments = source.get("tool_assignments") or []
    if not isinstance(servers, list) or not isinstance(assignments, list):
        print("invalid source: servers/tool_assignments must be arrays", file=sys.stderr)
        return 2

    if args.dry_run:
        print(f"Plan: servers={len(servers)}, tools={len(assignments)}, disable_local={args.disable_local}")
        return 0

    headers: Dict[str, str] = {}
    if args.token:
        headers["Authorization"] = f"Bearer {args.token}"
    base = args.base_url.rstrip("/")

    ok_server = 0
    ok_tool_catalog = 0
    ok_impl = 0
    failed = 0

    # 1) ensure server registry
    for s in servers:
        payload = {
            "serverCode": s.get("server_code"),
            "serverName": s.get("server_name") or s.get("server_code"),
            "description": s.get("description"),
            "baseUrl": s.get("base_url"),
            "transportType": s.get("transport_type") or "HTTP",
            "enabled": bool(s.get("enabled", True)),
        }
        if not payload["serverCode"]:
            print("[server] skip missing server_code")
            failed += 1
            continue
        status, body = http_post_json(f"{base}/mcp/migrate/server-registry", payload, headers, args.timeout)
        if status and 200 <= status < 300:
            ok_server += 1
        else:
            failed += 1
            print(f"[server] failed {payload['serverCode']} status={status} body={body[:300]}")
        if args.sleep_ms > 0:
            time.sleep(args.sleep_ms / 1000.0)

    # 2) for each tool: register to generate embedding, then upsert target server rows
    for a in assignments:
        tool_name = str(a.get("tool_name") or "").strip()
        server_code = str(a.get("server_code") or "").strip()
        if not tool_name or not server_code:
            failed += 1
            print("[assign] skip invalid item (tool_name/server_code required)")
            continue
        try:
            tool_json = read_tool_json(args.tool_json_dir, tool_name)
        except Exception as e:
            failed += 1
            print(f"[tool_json] failed {tool_name}: {e}")
            continue

        # 2.1 generate embedding from register path
        reg_payload = build_register_tool_payload(tool_json)
        status, body = http_post_json(f"{base}/mcp/tools", reg_payload, headers, args.timeout)
        if not (status and 200 <= status < 300):
            failed += 1
            print(f"[register_tool] failed {tool_name} status={status} body={body[:300]}")
            continue
        reg_body = safe_json_loads(body)
        embedding = reg_body.get("embedding")

        # 2.2 write target server catalog row
        catalog_payload = build_tool_catalog_payload(
            server_code=server_code,
            tool_name=tool_name,
            tool_json=tool_json,
            embedding=embedding,
            enabled=True,
        )
        status, body = http_post_json(f"{base}/mcp/migrate/tool-catalog", catalog_payload, headers, args.timeout)
        if status and 200 <= status < 300:
            ok_tool_catalog += 1
        else:
            failed += 1
            print(f"[tool_catalog] failed {tool_name}@{server_code} status={status} body={body[:300]}")
            continue

        # 2.3 write target server impl row
        impl_payload = build_impl_mapping_payload(server_code=server_code, tool_name=tool_name, tool_json=tool_json, enabled=True)
        status, body = http_post_json(f"{base}/mcp/migrate/tool-impl-mapping", impl_payload, headers, args.timeout)
        if status and 200 <= status < 300:
            ok_impl += 1
        else:
            failed += 1
            print(f"[tool_impl] failed {tool_name}@{server_code} status={status} body={body[:300]}")
            continue

        # optional: disable local rows to avoid global default bloat
        if args.disable_local:
            local_catalog_payload = build_tool_catalog_payload(
                server_code=LOCAL_SERVER_CODE,
                tool_name=tool_name,
                tool_json=tool_json,
                embedding=embedding,
                enabled=False,
            )
            status, body = http_post_json(f"{base}/mcp/migrate/tool-catalog", local_catalog_payload, headers, args.timeout)
            if not (status and 200 <= status < 300):
                failed += 1
                print(f"[disable_local_catalog] failed {tool_name} status={status} body={body[:300]}")
            local_impl_payload = build_impl_mapping_payload(
                server_code=LOCAL_SERVER_CODE,
                tool_name=tool_name,
                tool_json=tool_json,
                enabled=False,
            )
            status, body = http_post_json(f"{base}/mcp/migrate/tool-impl-mapping", local_impl_payload, headers, args.timeout)
            if not (status and 200 <= status < 300):
                failed += 1
                print(f"[disable_local_impl] failed {tool_name} status={status} body={body[:300]}")

        if args.sleep_ms > 0:
            time.sleep(args.sleep_ms / 1000.0)

    print(
        "Done. "
        f"server_ok={ok_server}, "
        f"tool_catalog_ok={ok_tool_catalog}, "
        f"tool_impl_ok={ok_impl}, "
        f"failed={failed}"
    )
    return 0 if failed == 0 else 1


if __name__ == "__main__":
    raise SystemExit(main())
