-- RETIRED (memory v2): legacy knowledge_base table is no longer the source of truth.
-- Canonical tables: knowledge_document + knowledge_chunk.
--
-- Migration path:
-- 1) apply memory_runtime_v2_schema.sql
-- 2) apply memory_runtime_v2_migration.sql
-- 3) optional cleanup in production after verification:
--      drop table if exists knowledge_base;
