-- RETIRED (memory v2): legacy luna_memory table is no longer the source of truth.
-- Canonical tables: task_working_memory / task_semantic_fact / task_episode / task_procedure_pattern.
--
-- Migration path:
-- 1) apply memory_runtime_v2_schema.sql
-- 2) apply memory_runtime_v2_migration.sql
-- 3) optional cleanup in production after verification:
--      drop table if exists luna_memory;
