-- RETIRED (memory v2): legacy user_preference table is no longer the source of truth.
-- Canonical tables: task_semantic_fact + relational_semantic_fact (+ relational_profile).
--
-- Migration path:
-- 1) apply memory_runtime_v2_schema.sql
-- 2) apply memory_runtime_v2_migration.sql
-- 3) optional cleanup in production after verification:
--      drop table if exists user_preference;
